# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsProfileSwitcher < Formula
  desc "You can easily switch AWS CLI profile settings."
  homepage "https://github.com/ryu022304/aws-profile-switcher"
  version "0.0.5"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryu022304/aws-profile-switcher/releases/download/v0.0.5/aws-profile-switcher_0.0.5_darwin_x86_64.tar.gz"
      sha256 "616bb4e9171ecce66f6aee43f1268ddeef1277af7d4359927c7475e28ef5a848"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryu022304/aws-profile-switcher/releases/download/v0.0.5/aws-profile-switcher_0.0.5_darwin_arm64.tar.gz"
      sha256 "9a8c021ad40f4a93ac239f85f5f53bcf7d1ccc6a8b5fa740ac881d34ac67673d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ryu022304/aws-profile-switcher/releases/download/v0.0.5/aws-profile-switcher_0.0.5_linux_x86_64.tar.gz"
      sha256 "31bbcaaafa5068f01c1cd3dc8ffc50a202248b84b956c97e8921ef750b0620f9"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryu022304/aws-profile-switcher/releases/download/v0.0.5/aws-profile-switcher_0.0.5_linux_arm64.tar.gz"
      sha256 "6db7d68fa6d44e5310c64f90b1f2c90b4b5842838f73d807faacb56a5695525c"
    end
  end

  def install
    bin.install "aws-ps"
    bin.install "aws-profile-switcher"
  end
end
