# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsProfileSwitcherGo < Formula
  desc "You can easily switch AWS CLI profile settings."
  homepage "https://github.com/ryu022304/aws-profile-switcher-go"
  version "0.0.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryu022304/aws-profile-switcher-go/releases/download/v0.0.1/aws-profile-switcher-go_0.0.1_darwin_x86_64.tar.gz"
      sha256 "0f9cb8eb3dc6de1e8e19edc73f3b589ba445ec87385f16bee85fb59777e60a8f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryu022304/aws-profile-switcher-go/releases/download/v0.0.1/aws-profile-switcher-go_0.0.1_darwin_arm64.tar.gz"
      sha256 "2cb46424fa656b32b6c3255ea7bc798d69a55a0c7e658c1daff13f8be0a32ea4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ryu022304/aws-profile-switcher-go/releases/download/v0.0.1/aws-profile-switcher-go_0.0.1_linux_x86_64.tar.gz"
      sha256 "067e99d49f187bc22bff1919869b2f2130cb93ceff50229c52df81f30169fcb6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryu022304/aws-profile-switcher-go/releases/download/v0.0.1/aws-profile-switcher-go_0.0.1_linux_arm64.tar.gz"
      sha256 "8b836e2ee5bd05502e717479449c52833f66bf0d54634dcaa614ad02bc442f25"
    end
  end

  def install
    bin.install "aws-ps"
    bin.install "aws-profile-switcher-go"
  end
end
